### ISSUE TITLE
Issues when there's special character in the text

### ISSUE THREAD

**Issue by jarretthuang** [jquery-textfill/jquery-textfill#61] opened 2017-10-26 17:24 UTC
Hi really good tool you made dude! I was using it for an asp.net web application when I came across this issue. If the text contains "<", it seems to be crashing the program. I tried "I <3 NY" and it crashed(infinite lagging) on me.

**Comment by jarretthuang** [comment] 2017-10-26 17:50
Actually I tested some other special characters, "$" doesn't work either. Same with empty text. Right now I'm using a helper function to validate text before calling textfill.

**Comment by GeekyMonkey** [comment] 2018-02-24 19:53
I'm not able to reproduce the issue on the sample page: http://jquery-textfill.github.io/example/

There have been quite a few changes merged in recently. Perhaps one if these fixed it.  If not, please give me a codepen or something showing the issue and I'll have another look.

Thanks for taking the time to report the issue.

**Closed by GeekyMonkey** 2018-02-24 19:53 UTC
